### ISSUE TITLE
Hard time to find existing subtitles for some shows

### ISSUE THREAD

**Issue by Modjor** [Amelandbor/service.subtitles.addic7ed#10]
Hi, thanks for maintaining this plugin - loving subtitles from addic7ed, and it's really cool to get them straight from Kodi.

However, I've been recently experiencing issue when looking for subtitles using this plugin.

The plugin search for subtitles, but after few seconds shows that it did not find any subtitles. However I can find completed subtitles on Addicted, and download them anonymously using my web browser.

I don't get this issue with all show, but recently I've been experiencing this issue with "Frontier" Dirk Gently's Holistic Detective Agency", where it can't find either of English of French subs. However, looking and downloading subs for "Emerald City" works great.

Not sure what's the issue here, I don't see anything related to this plugin in the kodi.log, and can't find any log file in the addon folders.

Any suggestion of what/where I should look in order to do some debugging?

Thanks!

**Comment by Amelandbor** [comment]
Probably something with those two shows being named differently in Kodi and addic7ed.
For that reason there is the [addic7ed_dict.txt](https://github.com/Amelandbor/service.subtitles.addic7ed/blob/master/addic7ed_dict.txt) file. The first value is the name in kodi, the second one is the name on the addic7ed website. 

You can always turn on debugging in the subtitle addon to get more info in your debug log.

**Comment by Modjor** [comment]
Yup, it was a difference between Addic7ed and theTVDB regarding the naming.
Here the line I've added to  addic7ed_dict.txt if anyone needs it:

`'Frontier (2016)': 'Frontier',`

I never noticed this correspondence file, so thanks for pointing this out!
Thanks

**Comment by Amelandbor** [comment]
Glad it solved it. You can always make a pull request if you want.

Op 27 jan. 2017 1:49 p.m. schreef "Modjor" <notifications@github.com>:

Yup, it was a difference between Addic7ed and theTVDB regarding the naming.
Here the line I've added to addic7ed_dict.txt if anyone needs it:

'Frontier (2016)': 'Frontier',

I never noticed this correspondence file, so thanks for pointing this out!
Thanks

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/Amelandbor/service.subtitles.addic7ed/issues/10#issuecomment-275658256>,
or mute the thread
